spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: root
    url: jdbc:h2:mem:testdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


messages:
  planDeleteFail: Plan Not deleted
  planDeletedSuccess: Plan Deleted Successfully
  planFail: Plan Not Saved
  planStatuSuccess: Plan status updated Successfully
  planStatusFail: Plan status failed
  planSuccess: Plan Saved Successfully
  planUpdatedFail: Plan Not updated
  planUpdatedSuccess: Plan Updated Successfully
